/* ═══════════════════════════════════════════════════════════
   DIGITAL IO — EVIDENCE TAB
   Attach photos, video, audio and documents to cases.
   Live camera capture, file select, print selected.
   ═══════════════════════════════════════════════════════════ */

// ── EVIDENCE ──
registerPage('evidence',renderEvidence);
async function renderEvidence(container){const all=await getEvidence();container.innerHTML=`<div class="page-header"><div><div class="page-title">🔬 Evidence & Media</div><div class="page-subtitle">${all.length} items</div></div><div style="display:flex;gap:8px;"><button class="btn btn-secondary btn-sm" onclick="selectAllEvidence()">☑️ Select All</button><button class="btn btn-secondary btn-sm" onclick="printSelectedEvidence()">🖨️ Print Selected</button><button class="btn btn-primary" onclick="openAddEvidenceModal()">+ Attach Evidence</button></div></div><div class="evidence-grid" id="evidence-grid">${all.length===0?`<div style="grid-column:1/-1;text-align:center;color:var(--text-muted);padding:40px;font-size:12px;">No evidence attached yet.</div>`:all.map(e=>`<div class="evidence-card" id="ev-card-${e.id}"><div class="evidence-thumb" style="position:relative;">${e.file_url?`<img src="${e.file_url}" style="width:100%;height:100%;object-fit:cover;" alt="">`:`<span style="font-size:36px;">${e.type==='Photo'?'📷':e.type==='Video'?'🎥':e.type==='Audio'?'🎙️':'📄'}</span>`}<input type="checkbox" class="ev-select-cb" data-id="${e.id}" style="position:absolute;top:8px;left:8px;width:16px;height:16px;accent-color:var(--accent);"></div><div class="evidence-info" onclick="viewEvidenceDetail('${e.id}')"><div class="evidence-name">${e.name}</div><div class="evidence-tag">${e.fir_number||'—'}</div><div style="display:flex;justify-content:space-between;margin-top:4px;"><span style="font-size:10px;background:var(--hover-bg);color:var(--text-muted);padding:2px 6px;border-radius:4px;">${e.type}</span><span style="font-size:9px;color:var(--text-faint);">${e.evidence_date||formatDate(e.created_at)}</span></div></div></div>`).join('')}</div>`;}
function selectAllEvidence(){document.querySelectorAll('.ev-select-cb').forEach(cb=>cb.checked=true);}
function printSelectedEvidence(){const sel=[...document.querySelectorAll('.ev-select-cb:checked')].map(cb=>cb.dataset.id);if(!sel.length){showToast('⚠️ Select at least one item.','error');return;}printContent(`<h1>🔬 Evidence Report</h1><p>${sel.length} item(s) selected</p>`,'Evidence Report');}
let cameraStream=null;
function openAddEvidenceModal(){openModal('➕ Attach Evidence',`<div style="display:flex;gap:8px;margin-bottom:14px;"><button class="btn btn-secondary btn-sm" onclick="openCamera()">📸 Live Camera</button><button class="btn btn-secondary btn-sm" onclick="openFileSelect()">📎 Select File</button></div><div id="camera-preview" style="display:none;margin-bottom:12px;"><video id="cam-video" style="width:100%;border-radius:8px;max-height:200px;" autoplay playsinline></video><div style="display:flex;gap:8px;margin-top:8px;"><button class="btn btn-primary btn-sm" onclick="snapPhoto()">📸 Capture</button><button class="btn btn-secondary btn-sm" onclick="stopCamera()">✕ Stop</button></div><canvas id="cam-canvas" style="display:none;"></canvas><img id="cam-snap" style="display:none;width:100%;border-radius:8px;margin-top:8px;border:2px solid var(--accent);" alt=""></div><div class="form-row"><div class="form-group"><label class="form-label">Name *</label><input class="form-input" id="ev-name" placeholder="Evidence name"></div><div class="form-group"><label class="form-label">Linked FIR *</label><input class="form-input" id="ev-fir-link" placeholder="e.g. 245/2025"></div></div><div class="form-row"><div class="form-group"><label class="form-label">Type</label><select class="form-input" id="ev-type-input"><option>Photo</option><option>Video</option><option>Audio</option><option>Document</option></select></div><div class="form-group"><label class="form-label">Date</label><input class="form-input" id="ev-date-input" placeholder="DD-MM-YYYY"></div></div><div class="form-group"><label class="form-label">Notes</label><textarea class="form-input" id="ev-notes-input" rows="2" placeholder="Description..."></textarea></div>`,`<button class="btn btn-secondary" onclick="stopCamera();closeModal()">Cancel</button><button class="btn btn-primary" onclick="saveEvidenceItem()">💾 Attach</button>`);}
function openCamera(){document.getElementById('camera-preview').style.display='block';navigator.mediaDevices?.getUserMedia({video:{facingMode:'environment'}}).then(stream=>{cameraStream=stream;document.getElementById('cam-video').srcObject=stream;}).catch(()=>showToast('⚠️ Camera not available.','error'));}
function stopCamera(){cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;}
function snapPhoto(){const v=document.getElementById('cam-video'),c=document.getElementById('cam-canvas'),s=document.getElementById('cam-snap');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);s.src=c.toDataURL('image/jpeg',0.9);s.style.display='block';v.style.display='none';stopCamera();const ni=document.getElementById('ev-name');if(ni&&!ni.value)ni.value='Live Photo '+new Date().toLocaleString('en-PK');document.getElementById('ev-type-input').value='Photo';showToast('✅ Photo captured!','success');}
function openFileSelect(){const i=document.createElement('input');i.type='file';i.accept='image/*,video/*,audio/*,.pdf,.doc,.docx';i.onchange=e=>{const f=e.target.files[0];if(!f)return;const ni=document.getElementById('ev-name');if(ni&&!ni.value)ni.value=f.name;const ti=document.getElementById('ev-type-input');if(ti){if(f.type.startsWith('image'))ti.value='Photo';else if(f.type.startsWith('video'))ti.value='Video';else if(f.type.startsWith('audio'))ti.value='Audio';else ti.value='Document';}showToast('📎 File selected: '+f.name,'success');};i.click();}
async function saveEvidenceItem(){const name=document.getElementById('ev-name').value.trim(),fir=document.getElementById('ev-fir-link').value.trim();if(!name||!fir){showToast('⚠️ Name and FIR are required.','error');return;}try{await addEvidence({name,fir_number:fir,type:document.getElementById('ev-type-input').value,evidence_date:document.getElementById('ev-date-input').value,notes:document.getElementById('ev-notes-input').value,is_readonly:true});stopCamera();closeModal();showToast('✅ Evidence attached: '+name,'success');renderEvidence(document.getElementById('page-content'));}catch(err){showToast('❌ Error: '+err.message,'error');}}
async function viewEvidenceDetail(id){const all=await getEvidence(),e=all.find(x=>x.id===id);if(!e)return;openModal('🔬 Evidence Details',`<div>${[['Name',e.name],['FIR',e.fir_number||'—'],['Type',e.type],['Date',e.evidence_date||'—'],['Notes',e.notes||'—']].map(([k,v])=>`<div class="detail-row"><span class="detail-key">${k}</span><span class="detail-val">${v}</span></div>`).join('')}</div><div style="text-align:center;padding:16px;font-size:48px;">${e.type==='Photo'?'📷':e.type==='Video'?'🎥':e.type==='Audio'?'🎙️':'📄'}</div>`,`<button class="btn btn-secondary" onclick="closeModal()">Close</button><button class="btn btn-danger btn-sm" onclick="closeModal();doDeleteEvidence('${id}')">🗑️ Delete</button>`);}
async function doDeleteEvidence(id){try{await deleteEvidence(id);showToast('🗑️ Evidence deleted.');renderEvidence(document.getElementById('page-content'));}catch(err){showToast('❌ Error: '+err.message,'error');}}


