/* ═══════════════════════════════════════════════════════════
   DIGITAL IO — LAW LIBRARY TAB
   Reference cards for PPC, CrPC, CNSA, ATA and other Acts.
   ═══════════════════════════════════════════════════════════ */

// ── LAW ──
registerPage('law',renderLaw);
const LAWS=[{name:'Pakistan Penal Code',short:'PPC 1860',icon:'⚖️',sections:'511 Sections',color:'#38bdf8',url:'https://pakistancode.gov.pk/english/index.php'},{name:'Code of Criminal Procedure',short:'CrPC 1898',icon:'📜',sections:'565 Sections',color:'#a78bfa',url:'https://pakistancode.gov.pk/english/index.php'},{name:'Motor Vehicle Ordinance',short:'MVO',icon:'🚗',sections:'84 Sections',color:'#22c55e',url:'https://punjabcode.punjab.gov.pk/urdu/index'},{name:'Control of Narcotic Substances',short:'CNSA 1997',icon:'💊',sections:'68 Sections',color:'#ef4444',url:'https://pakistancode.gov.pk/english/index.php'},{name:'Arms Ordinance',short:'Arms Ord. 1965',icon:'🔫',sections:'25 Sections',color:'#f59e0b',url:'https://pakistancode.gov.pk/english/index.php'},{name:'Anti-Terrorism Act',short:'ATA 1997',icon:'🛡️',sections:'48 Sections',color:'#f97316',url:'https://pakistancode.gov.pk/english/index.php'},{name:'Women Protection Act',short:'WPA 2006',icon:'👩‍⚖️',sections:'30 Sections',color:'#ec4899',url:'https://punjabcode.punjab.gov.pk/urdu/index'},{name:'Qanun-e-Shahadat',short:'Evidence Act 1984',icon:'📋',sections:'166 Articles',color:'#14b8a6',url:'https://pakistancode.gov.pk/english/index.php'},{name:'Anti-Rape Laws',short:'CPLC Act 2021',icon:'⚡',sections:'29 Sections',color:'#6366f1',url:'https://pakistancode.gov.pk/english/index.php'},{name:'Punjab Food Authority Act',short:'PFA 2011',icon:'🍽️',sections:'40 Sections',color:'#84cc16',url:'https://punjabcode.punjab.gov.pk/urdu/index'},{name:'Electricity Theft Laws',short:'PECA / Electricity Act',icon:'⚡',sections:'Multiple',color:'#facc15',url:'https://pakistancode.gov.pk/english/index.php'},{name:'Prohibition Act',short:'Prohibition Act',icon:'🚫',sections:'18 Sections',color:'#94a3b8',url:'https://pakistancode.gov.pk/english/index.php'}];
function renderLaw(container){container.innerHTML=`<div class="page-header"><div style="display:flex;align-items:center;gap:10px;margin-bottom:8px;"><button onclick="showPage('dashboard',document.querySelector('.nav-item'))" style="background:var(--bg-secondary);border:1px solid var(--border);border-radius:8px;padding:6px 14px;font-size:13px;font-weight:700;cursor:pointer;color:var(--text-secondary);font-family:'Jameel Noori Nastaleeq',serif;display:inline-flex;align-items:center;gap:6px;" onmouseover="this.style.borderColor='var(--accent)'" onmouseout="this.style.borderColor='var(--border)'">← واپس</button><div class="page-title">⚖️ قانونی لائبریری</div></div></div><div class="search-bar"><input class="search-input" id="law-search" placeholder="Search laws..." oninput="filterLaws(this.value)"></div><div style="display:flex;gap:8px;margin-bottom:14px;"><button class="btn btn-secondary btn-sm" onclick="window.open('https://punjabcode.punjab.gov.pk/urdu/index')">🔗 Punjab Code</button><button class="btn btn-secondary btn-sm" onclick="window.open('https://pakistancode.gov.pk/english/index.php')">🔗 Pakistan Code</button><button class="btn btn-secondary btn-sm" onclick="window.open('https://data.lhc.gov.pk/dynamic/approved_judgments_result_new.php')">🔗 LHC Judgments</button></div><div class="law-grid" id="law-grid">${renderLawCards(LAWS)}</div>`;}
function renderLawCards(items){return items.map(l=>`<div class="law-card" onclick="window.open('${l.url}')"><div style="font-size:28px;margin-bottom:8px;">${l.icon}</div><div style="font-size:13px;font-weight:600;margin-bottom:4px;">${l.name}</div><div style="font-size:11px;color:var(--text-muted);margin-bottom:8px;">${l.short}</div><div style="font-size:10px;color:${l.color};">${l.sections}</div></div>`).join('');}
function filterLaws(q){const s=q.toLowerCase(),filtered=s?LAWS.filter(l=>l.name.toLowerCase().includes(s)||l.short.toLowerCase().includes(s)):LAWS,grid=document.getElementById('law-grid');if(grid)grid.innerHTML=renderLawCards(filtered);}

