/* ═══════════════════════════════════════════════════════════
   DIGITAL IO — REMINDERS TAB
   Create, complete and delete case-linked reminders.
   ═══════════════════════════════════════════════════════════ */

// ── REMINDERS ──
registerPage('reminders',renderReminders);
async function renderReminders(container){const rem=await getReminders();container.innerHTML=`<div class="page-header"><div class="page-title">🔔 Reminders</div><button class="btn btn-primary" onclick="openAddReminderModal()">+ Add Reminder</button></div><div class="card">${rem.length===0?`<div style="text-align:center;padding:30px;color:var(--text-muted);font-size:12px;">No reminders. <a onclick="openAddReminderModal()">Add your first →</a></div>`:rem.map(r=>`<div style="display:flex;align-items:center;gap:10px;padding:10px 0;border-bottom:1px solid var(--border-light);"><input type="checkbox" ${r.is_done?'checked':''} onchange="toggleReminder('${r.id}',this.checked)" style="accent-color:var(--accent);width:16px;height:16px;"><div style="flex:1;"><div style="font-size:13px;${r.is_done?'text-decoration:line-through;color:var(--text-muted);':''}">${r.text}</div><div style="font-size:10px;color:var(--text-muted);">${r.linked_fir?'FIR: '+r.linked_fir+' · ':''}${formatDate(r.reminder_date)}</div></div><span class="pill ${r.priority==='high'?'pill-red':r.priority==='medium'?'pill-amber':'pill-blue'}">${r.priority}</span><button class="btn btn-danger btn-sm" onclick="doDeleteReminder('${r.id}')">✕</button></div>`).join('')}</div>`;}
function openAddReminderModal(){openModal('➕ Add Reminder',`<div class="form-group"><label class="form-label">Reminder Text *</label><input class="form-input" id="rem-text" placeholder="e.g. Submit challan for FIR 245/2025"></div><div class="form-row"><div class="form-group"><label class="form-label">Date</label><input class="form-input" id="rem-date" type="date"></div><div class="form-group"><label class="form-label">Priority</label><select class="form-input" id="rem-priority"><option value="high">🔴 High</option><option value="medium" selected>🟡 Medium</option><option value="low">🔵 Low</option></select></div></div><div class="form-group"><label class="form-label">Linked FIR (optional)</label><input class="form-input" id="rem-fir" placeholder="e.g. 245/2025"></div>`,`<button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="saveReminder()">💾 Save</button>`);}
async function saveReminder(){const text=document.getElementById('rem-text').value.trim();if(!text){showToast('⚠️ Text required.','error');return;}try{await addReminder({text,reminder_date:document.getElementById('rem-date').value,priority:document.getElementById('rem-priority').value,linked_fir:document.getElementById('rem-fir').value.trim()});closeModal();showToast('✅ Reminder added!','success');await updateBadges();renderReminders(document.getElementById('page-content'));}catch(err){showToast('❌ Error: '+err.message,'error');}}
async function toggleReminder(id,done){await updateReminder(id,{is_done:done});await updateBadges();}
async function doDeleteReminder(id){await deleteReminder(id);showToast('🗑️ Reminder deleted.');await updateBadges();renderReminders(document.getElementById('page-content'));}

