/* ═══════════════════════════════════════════════════════════
   DIGITAL IO — ADVANCED SEARCH TAB
   Search cases by FIR, name, CNIC, cell, section, status.
   ═══════════════════════════════════════════════════════════ */

// ── SEARCH ──
registerPage('search',renderSearch);
async function renderSearch(container){container.innerHTML=`<div class="page-header"><div class="page-title">🔍 Advanced Search</div></div><div class="card" style="margin-bottom:16px;"><div class="card-title">SEARCH PARAMETERS</div><div class="form-row"><div class="form-group"><label class="form-label">FIR Number</label><input class="form-input" id="sr-fir" placeholder="e.g. 245/2025"></div><div class="form-group"><label class="form-label">Accused / Complainant Name</label><input class="form-input" id="sr-name" placeholder="Full or partial name"></div></div><div class="form-row"><div class="form-group"><label class="form-label">CNIC</label><input class="form-input" id="sr-cnic" placeholder="XXXXX-XXXXXXX-X" oninput="autoFormatCNIC(this)"></div><div class="form-group"><label class="form-label">Cell Number</label><input class="form-input" id="sr-cell" placeholder="0XXX-XXXXXXX" oninput="autoFormatCell(this)"></div></div><div class="form-row"><div class="form-group"><label class="form-label">Section of Law</label><input class="form-input" id="sr-section" placeholder="e.g. 302 PPC"></div><div class="form-group"><label class="form-label">Status</label><select class="form-input" id="sr-status"><option value="">Any Status</option>${Object.entries(STATUS_LABELS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div></div><div style="display:flex;gap:8px;"><button class="btn btn-primary" onclick="runAdvancedSearch()">🔍 Search</button><button class="btn btn-secondary" onclick="clearSearch()">Clear</button></div></div><div class="card" id="search-results"><div class="card-title">RESULTS</div><div style="color:var(--text-faint);font-size:12px;">Enter criteria above and click Search.</div></div>`;}
async function runAdvancedSearch(){const results=await advancedSearch({fir:document.getElementById('sr-fir').value.trim(),name:document.getElementById('sr-name').value.trim(),cnic:document.getElementById('sr-cnic').value.trim(),cell:document.getElementById('sr-cell').value.trim(),section:document.getElementById('sr-section').value.trim(),status:document.getElementById('sr-status').value});const el=document.getElementById('search-results');if(!el)return;el.innerHTML=results.length===0?`<div class="card-title">RESULTS</div><div style="color:var(--text-muted);font-size:12px;padding:20px 0;text-align:center;">No cases found.</div>`:`<div class="card-title">RESULTS — ${results.length} case(s) found</div><table class="data-table"><thead><tr><th>FIR No.</th><th>Accused</th><th>CNIC</th><th>Cell</th><th>Section</th><th>Status</th><th>Action</th></tr></thead><tbody>${results.map(c=>`<tr><td><span class="fir-num" onclick="viewCase('${c.id}')">${c.fir_number}</span></td><td>${c.complainant||'—'}</td><td style="font-family:var(--font-mono);font-size:11px;">${formatCNIC(c.accused_cnic)}</td><td style="font-family:var(--font-mono);font-size:11px;">${formatCell(c.accused_cell)}</td><td style="font-size:11px;">${c.section_of_law||'—'}</td><td><span class="pill ${STATUS_CLASSES[c.status]||'pill-blue'}">${STATUS_LABELS[c.status]||c.status}</span></td><td><button class="btn btn-secondary btn-sm" onclick="viewCase('${c.id}')">View</button></td></tr>`).join('')}</tbody></table>`;}
function clearSearch(){['sr-fir','sr-name','sr-cnic','sr-cell','sr-section'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});document.getElementById('sr-status').value='';const el=document.getElementById('search-results');if(el)el.innerHTML=`<div class="card-title">RESULTS</div><div style="color:var(--text-faint);font-size:12px;">Enter criteria above and click Search.</div>`;}

