/* ═══════════════════════════════════════════════════════════
   DIGITAL IO — SETTINGS & PROFILE TAB
   Officer profile edit, profile photo, security status.
   ═══════════════════════════════════════════════════════════ */

// ── SETTINGS ──
registerPage('settings',renderSettings);
function renderSettings(container){const officer=currentOfficer||{};container.innerHTML=`<div class="page-header"><div class="page-title">⚙️ Settings & Profile</div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;"><div class="card"><div class="card-title">👮 OFFICER PROFILE</div><div class="form-group"><label class="form-label">Full Name</label><input class="form-input" id="set-name" value="${officer.full_name||''}"></div><div class="form-group"><label class="form-label">Badge / Service Number</label><input class="form-input" id="set-badge" value="${officer.badge_number||''}"></div><div class="form-group"><label class="form-label">Designation</label><input class="form-input" id="set-designation" value="${officer.designation||''}"></div><div class="form-group"><label class="form-label">Police Station</label><input class="form-input" id="set-station" value="${officer.station||''}"></div><div class="form-group"><label class="form-label">District</label><input class="form-input" id="set-district" value="${officer.district||''}"></div><button class="btn btn-primary" onclick="saveProfileSettings()">💾 Save Profile</button></div><div class="card"><div class="card-title">🖼️ PROFILE PHOTO</div><div style="text-align:center;padding:16px 0;"><div id="settings-avatar" style="width:80px;height:80px;border-radius:50%;background:linear-gradient(135deg,var(--accent-dark),var(--accent));margin:0 auto 12px;display:flex;align-items:center;justify-content:center;font-size:28px;font-weight:800;color:#fff;overflow:hidden;">${localStorage.getItem('dio_profile_photo')?`<img src="${localStorage.getItem('dio_profile_photo')}" style="width:100%;height:100%;object-fit:cover;border-radius:50%;" alt="">`:(officer.full_name?.split(' ').map(w=>w[0]).join('').slice(0,2).toUpperCase()||'IO')}</div><button class="btn btn-secondary btn-sm" onclick="changeProfilePhoto()">📷 Change Photo</button></div><div class="card-title" style="margin-top:16px;">🔐 SECURITY</div><div style="font-size:11px;color:var(--green);">✅ MFA Active · ✅ Audit Logging · ✅ Encrypted Data</div></div></div>`;}
async function saveProfileSettings(){try{await updateOfficerProfile({full_name:document.getElementById('set-name').value.trim(),badge_number:document.getElementById('set-badge').value.trim(),designation:document.getElementById('set-designation').value.trim(),station:document.getElementById('set-station').value.trim(),district:document.getElementById('set-district').value.trim()});updateSidebarProfile();showToast('✅ Profile updated!','success');}catch(err){showToast('❌ Error: '+err.message,'error');}}
function changeProfilePhoto(){const i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{const src=ev.target.result;try{localStorage.setItem('dio_profile_photo',src);}catch(e){}document.querySelectorAll('.officer-card-avatar,.sidebar-avatar,#settings-avatar').forEach(el=>{el.innerHTML=`<img src="${src}" style="width:100%;height:100%;object-fit:cover;border-radius:50%;" alt="">`;});showToast('✅ Profile photo updated!','success');};r.readAsDataURL(f);};i.click();}

